eks_admins_iam_role = "eks-admins"
vpc_name               = "eks-vpc"
region                 = "us-west-2"
eks_cluster_domain     = "micbegin.people.aws.dev"
acm_certificate_domain = "*.micbegin.people.aws.dev"
workloads_org          = "aws-samples"
workloads_path         = "argocd"
workloads_repo_url     = "https://github.com/aws-samples/eks-blueprints-actions-workflow.git"
