apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: karpenter-node-pools
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: karpenter
    server: "{{ .Values.spec.destination.server }}"
  source:
    repoURL: "{{ .Values.spec.source.repoURL }}"
    targetRevision: "{{ .Values.spec.source.targetRevision }}"
    path: helm/karpenter-node-pools
    helm:
      valuesObject:
        clusterName: "{{ .Values.clusterName }}"
        iamRoleName: "{{ .Values.karpenter.iamRoleName }}"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
