---
apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: {{ .Values.karpenter.settings.clusterName }}-default
spec:
  disruption:
    consolidationPolicy: WhenUnderutilized
  expireAfter: 24h
  template:
    spec:
      requirements:
        - key: "kubernetes.io/arch"
          operator: In
          values: ["amd64"]
        - key: "karpenter.sh/capacity-type"
          operator: In
          values: ["spot", "on-demand"]
      nodeClassRef:
        apiVersion: karpenter.k8s.aws/v1beta1
        kind: EC2NodeClass
        name: default
---
apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: default
spec:
  role: {{ .Values.karpenter.serviceAccount.iamRoleArn }}
  amiFamily: Bottlerocket
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery/{{ .Values.karpenter.settings.clusterName }}: {{ .Values.karpenter.settings.clusterName }}
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery/{{ .Values.karpenter.settings.clusterName }}: {{ .Values.karpenter.settings.clusterName }}
  tags:
    karpenter.sh/discovery/{{ .Values.karpenter.settings.clusterName }}: {{ .Values.karpenter.settings.clusterName }}
