name: tfsec

on:
  push:
  pull_request:

  workflow_dispatch:


jobs:
  scan:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Run tfsec
        uses: aquasecurity/tfsec-action@v1.0.0
        with:
          additional_args: '--concise-output --exclude-downloaded-modules'
